### ISSUE TITLE
Create AI for Opponent

### ISSUE THREAD

**Issue by sarahbau** [enj/cloned#21]
Determine how AI controlled opponent will make decisions on movement and attacks, and reactions to players’ movements.

**Comment by sarahbau** [comment]
I found out that game maker can simulate key presses. This might be an easy way of allowing either a human or AI to control player 2. Right now I just have it randomly punching and kicking.

**Comment by sarahbau** [comment]
I have a working AI script right now, but it's pretty simple. Still way better than twitchypong. I moved all of the player actions into separate scripts so they can be easily called by any player or ai controller we make.

**Comment by enj** [comment]
All good.
